export const CREATE_BILL_LOADING = "bills/CREATE_BILL_LOADING";
export const CREATE_BILL_SUCCESS = "bills/CREATE_BILL_SUCCESS";
export const CREATE_BILL_FAIL = "bills/CREATE_BILL_FAIL";
export const CREATE_BILL_RESET = "bills/CREATE_BILL_RESET";

export const SEARCH_BILL_LOADING = "bills/SEARCH_BILL_LOADING";
export const SEARCH_BILL_SUCCESS = "bills/SEARCH_BILL_SUCCESS";
export const SEARCH_BILL_FAIL = "bills/SEARCH_BILL_FAIL";

export const GET_BILL_LOADING = "bills/GET_BILL_LOADING";
export const GET_BILL_SUCCESS = "bills/GET_BILL_SUCCESS";
export const GET_BILL_FAIL = "bills/GET_BILL_FAIL";

export const UPDATE_BILL_LOADING = "bills/UPDATE_BILL_LOADING";
export const UPDATE_BILL_SUCCESS = "bills/UPDATE_BILL_SUCCESS";
export const UPDATE_BILL_FAIL = "bills/UPDATE_BILL_FAIL";
export const UPDATE_BILL_RESET = "bills/UPDATE_BILL_RESET";
